/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.Dimension;
import javax.swing.JDesktopPane;
import javax.swing.JInternalFrame;
import model.bean.Vendedor;

/**
 *
 * @author USUARIO
 */
public class TipoDeCadastro extends javax.swing.JInternalFrame {
    private JDesktopPane PainelDesktop;

    /**
     * Creates new form NovoJInternalFrame
     */
    
    
    public TipoDeCadastro(JDesktopPane pd) {
        initComponents();
        this.PainelDesktop=pd;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        TipoDeCadastro = new javax.swing.JComboBox<>();
        MostrarTelaDeCadastro = new javax.swing.JButton();

        setBorder(null);
        setOpaque(true);

        jLabel1.setText("O QUE DESEJA CADASTRAR");

        TipoDeCadastro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Livro", "Vendedor", "Cliente" }));
        TipoDeCadastro.setBorder(null);
        TipoDeCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TipoDeCadastroActionPerformed(evt);
            }
        });

        MostrarTelaDeCadastro.setText("Pronto");
        MostrarTelaDeCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MostrarTelaDeCadastroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(137, 137, 137)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(TipoDeCadastro, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(173, 173, 173)
                        .addComponent(MostrarTelaDeCadastro)))
                .addContainerGap(137, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(TipoDeCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addComponent(MostrarTelaDeCadastro)
                .addGap(30, 30, 30))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TipoDeCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TipoDeCadastroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TipoDeCadastroActionPerformed

    private void MostrarTelaDeCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MostrarTelaDeCadastroActionPerformed
       
        switch (TipoDeCadastro.getSelectedItem().toString()){
             
            case "Vendedor":
                JInternalFrame TelaVendedor = new TelaCadastroVendedor();
                
                this.PainelDesktop.removeAll();
                this.PainelDesktop.add(TelaVendedor);
                TelaVendedor.setVisible(true);
                
            
        }
        
        switch (TipoDeCadastro.getSelectedItem().toString()){
        case "Livro":
                JInternalFrame TelaLivro = new TelaCadastroLivro();
                
                this.PainelDesktop.removeAll();
                this.PainelDesktop.add(TelaLivro);
                TelaLivro.setVisible(true);
        }
        
    }//GEN-LAST:event_MostrarTelaDeCadastroActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton MostrarTelaDeCadastro;
    private javax.swing.JComboBox<String> TipoDeCadastro;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
