/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.Dimension;
import javax.swing.JDesktopPane;
import javax.swing.JInternalFrame;
import model.bean.Vendedor;

/**
 *
 * @author USUARIO
 */
public class TipoDeCadastro extends javax.swing.JInternalFrame {
    private JDesktopPane PainelDesktop;

    /**
     * Creates new form NovoJInternalFrame
     */
    
    
    public TipoDeCadastro(JDesktopPane pd) {
        initComponents();
        this.PainelDesktop=pd;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        TipoDeCadastro = new javax.swing.JComboBox<>();
        MostrarTelaDeCadastro = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setBorder(null);
        setOpaque(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("O QUE DESEJA CADASTRAR");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, -1, -1));

        TipoDeCadastro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Livro", "Vendedor" }));
        TipoDeCadastro.setBorder(null);
        TipoDeCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TipoDeCadastroActionPerformed(evt);
            }
        });
        getContentPane().add(TipoDeCadastro, new org.netbeans.lib.awtextra.AbsoluteConstraints(137, 57, 136, -1));

        MostrarTelaDeCadastro.setText("Pronto");
        MostrarTelaDeCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MostrarTelaDeCadastroActionPerformed(evt);
            }
        });
        getContentPane().add(MostrarTelaDeCadastro, new org.netbeans.lib.awtextra.AbsoluteConstraints(173, 118, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/thinkstockphotos-541137274-e1481892729817.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-60, -70, 480, 260));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TipoDeCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TipoDeCadastroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TipoDeCadastroActionPerformed

    private void MostrarTelaDeCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MostrarTelaDeCadastroActionPerformed
       
        switch (TipoDeCadastro.getSelectedItem().toString()){
             
            case "Vendedor":
                JInternalFrame TelaVendedor = new TelaCadastroVendedor();
                
                this.PainelDesktop.removeAll();
                this.PainelDesktop.add(TelaVendedor);
                TelaVendedor.setVisible(true);
                
            
        }
        
        switch (TipoDeCadastro.getSelectedItem().toString()){
        case "Livro":
                JInternalFrame TelaLivro = new TelaCadastroLivro();
                
                this.PainelDesktop.removeAll();
                this.PainelDesktop.add(TelaLivro);
                TelaLivro.setVisible(true);
        }
        
    }//GEN-LAST:event_MostrarTelaDeCadastroActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton MostrarTelaDeCadastro;
    private javax.swing.JComboBox<String> TipoDeCadastro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
